# Site settings
title: Web Developer or Bust!
header-img: img/home-bg.png
email: kkterai@gmail.com
copyright_name: kkterai
description: > # this means to ignore newlines until "baseurl:"
  Learning Code and other Stories
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: kkterai
github_username:  kkterai
learn_profile: kkterai
email_username: kkterai@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
